source('code/functions/helper.R')
source('code/functions/gridsearch.R')
source('code/functions/search_patterns.R')
source('code/functions/tac.R')
source('code/functions/simulation.R')
source('code/functions/cleanup.R')