source('chapter_3/code/functions/helper.R')
source('chapter_3/code/functions/gridsearch.R')
source('chapter_3/code/functions/search_patterns.R')
source('chapter_3/code/functions/tac.R')
source('chapter_3/code/functions/simulation.R')
source('chapter_3/code/functions/cleanup.R')
